### ISSUE TITLE
Running the go-stream-perf-test:dev container returns a fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-stream-go-client#71]
I was not expecting this `deadlock` error when running `go-stream-perf-test:dev` container image with the `--help` flag:

```
root@w:~# docker run --name rabbitmq-stream-clients -it --rm --network host pivotalrabbitmq/go-stream-perf-test:dev --help
RabbitMQ Golang PerfTest for streaming queues

Usage:
  PerfTest [command]

Available Commands:
  help        Help about any command
  silent      NewProducer a silent simulation
  version     Print CLI version

Flags:
      --batch-size int                         Batch Size, from 1 to 200 (default 100)
      --consumer-offset string                 Staring consuming, ex: first,last,next of number (default "first")
      --consumers int                          Number of Consumers (default 1)
      --consumers-per-client int               Consumers Per Client (default 3)
      --debug-logs                             Enable debug logs
      --exit-on-error                          Close the app in case of error (default true)
      --fixed-body int                         Body size
  -h, --help                                   help for PerfTest
      --max-age int                            Stream Age in hours, e.g. 1,2.. 24 , etc.
      --max-length-bytes string                Stream max length bytes, e.g. 10MB, 50GB, etc. (default "0")
      --print-stats                            Print stats (default true)
      --publishers int                         Number of Publishers (default 1)
      --publishers-per-client int              Publishers Per Client (default 3)
      --rate int                               Limit publish rate
      --stream-max-segment-size-bytes string   Stream segment size bytes, e.g. 10MB, 1GB, etc. (default "500MB")
      --streams strings                        Stream names (default [perf-test-go])
      --uris strings                           Broker URLs (default [rabbitmq-stream://guest:guest@localhost:5552/%2f])
      --variable-body int                      Variable body size
      --variable-rate int                      Variable rate to value

Use "PerfTest [command] --help" for more information about a command.
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x977570)
        /usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0x977568)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
main.main()
        /go/src/github.com/rabbitmq/rabbitmq-stream-go-client/perfTest/perftest.go:14 +0x5e
```

What did I do wrong?

FWIW, this is the initial command that I ran, and I thought that I go some flags wrong: `docker run --name rabbitmq-stream-clients -it --rm --network host pivotalrabbitmq/go-stream-perf-test:dev --uris rabbitmq-stream://guest:guest@w:5552/%2f --streams stream1 --max-length-bytes 1GB --publishers 2 --consumers 3`

When I have my answer, I will add an example to the README so that it helps others.

**Comment by gerhard** [comment]
OK, I understand my issue: I interpreted `PerfTest [command]` as an **optional** command. It was meant to be `PerfTest <command>`. Will leave this open as a first thing to tackle tomorrow. All good 👍🏻

**Comment by Gsantomaggio** [comment]
closed via https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/72
