### ISSUE TITLE
panic: nil reference when target server is down

### ISSUE THREAD

**Issue by victorges** [rabbitmq/rabbitmq-stream-go-client#96]
Hey all! So we've been getting a nil reference panic every time we roll out the RabbitMQ servers in our infrastructure. It seems to be inside the environment/broker connection logic, after `clientLocator.BrokerForConsumer` apparently returns a `nil` broker and no error? Not sure if possible, but here follows the stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x702eff]
goroutine 1 [running]:
github.com/rabbitmq/rabbitmq-stream-go-client/pkg/stream.(*Broker).hostPort(...)
	/go/pkg/mod/github.com/rabbitmq/rabbitmq-stream-go-client@v0.1.0-beta.0.20211027081212-fd5e6d497413/pkg/stream/brokers.go:128
github.com/rabbitmq/rabbitmq-stream-go-client/pkg/stream.(*consumersEnvironment).NewSubscriber(0xc0000cc1c0, 0xc00024e160, 0xc00002e048, 0x13, 0xc00022c3a0, 0xc000242380, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rabbitmq/rabbitmq-stream-go-client@v0.1.0-beta.0.20211027081212-fd5e6d497413/pkg/stream/enviroment.go:632 +0xff
github.com/rabbitmq/rabbitmq-stream-go-client/pkg/stream.(*Environment).NewConsumer(0xc0002020f0, 0xc00002e048, 0x13, 0xc00022c3a0, 0xc000242380, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rabbitmq/rabbitmq-stream-go-client@v0.1.0-beta.0.20211027081212-fd5e6d497413/pkg/stream/enviroment.go:197 +0x113

<from here down, stack trace from our own code>
github.com/livepeer/livepeer-data/pkg/event.(*strmConsumer).ConsumeChan.func2(0x0, 0xc000206038, 0xc000191b58, 0x70c707)
	/app/pkg/event/stream_consumer.go:91 +0xc5
github.com/livepeer/livepeer-data/pkg/event.newReconnectingConsumer(0x8524b8, 0xc000242340, 0xc00002e048, 0x13, 0xc000242300, 0x0, 0x784e40, 0xc00022c240)
	/app/pkg/event/stream_consumer.go:156 +0x50
github.com/livepeer/livepeer-data/pkg/event.(*strmConsumer).ConsumeChan(0xc00023a040, 0x8524b8, 0xc000242100, 0xc00002e048, 0x13, 0xc000228300, 0xc0002420c0, 0x1, 0x0, 0x0, ...)
	/app/pkg/event/stream_consumer.go:95 +0x1a8
github.com/livepeer/livepeer-data/pkg/event.(*strmConsumer).Consume(0xc00023a040, 0x8524b8, 0xc0000208c0, 0xc00002e048, 0x13, 0xc000228300, 0xc0002420c0, 0x1, 0x84c180, 0xc000240000, ...)
	/app/pkg/event/stream_consumer.go:109 +0x95
github.com/livepeer/livepeer-data/health.(*Core).Start(0xc000240000, 0x8524b8, 0xc0000208c0, 0xc000202108, 0x852678)
	/app/health/core.go:75 +0x351
main.main()
	/app/cmd/analyzer/analyzer.go:105 +0x61f
```

We were already getting the issue before, but I thought that updating the library version should fix it. I [just tested on the latest commit from yesterday](https://github.com/livepeer/livepeer-data/blob/31ba56d6b7be7bb0b7ebac0267c776b0275d178d/go.sum#L226) though ([fd5e6d](https://github.com/rabbitmq/rabbitmq-stream-go-client/commit/fd5e6d497413ab75e95957790e2af943000e7af3)), but the issue still happens, so maybe it needs a direct fix. Would be happy to fix it myself, but would need some help debugging/indications on how it should be ideally fixed. Thanks!

**Comment by victorges** [comment]
Thanks @Gsantomaggio ! Just submitted a review on the PR. I think I like the idea of a specific error type, as that might be used in some retry-after vs fatal error logic on the client side. Added a comment on the PR about that as well.
